-- Add migration script here
create table if not exists subscription_group
(
    id          bigint generated by default as identity,
    name        varchar     not null default '' unique,
    description varchar     not null default '',
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp
);

alter table subscription_group
    add constraint subscription_group_id_pk primary key (id);

create table if not exists subscriber
(
    id         bigint generated by default as identity,
    email      varchar     not null default '',
    group_id   bigint      not null references subscription_group (id) on delete cascade,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

alter table subscriber
    add constraint subscriber_id_pk primary key (id);
